routes/web.php
    }
});

Auth::routes();


Route::get('/beranda', 'HomeController@index')->name('beranda');
Route::match(['get','post'],'home/get-notif', 'HomeController@getNotif');
Route::match(['get','post'],'home/update-notif', 'HomeController@updateNotif');
Route::match(['get','post'],'home/delete-notif', 'HomeController@deleteNotif');

Route::get('user/load-data','UserController@loadData');
Route::get('user/json','UserController@json');
Route::get('user/activate/{id}','UserController@activate');
Route::get('user/update/{id}','UserController@update');
Route::get('user/deactivate/{id}','UserController@deactivate');
Route::get('user/{id}/reset','UserController@reset');
Route::resource('user','UserController');
Route::delete('user/{id}/restore','UserController@restore');

Route::get('autocomplete/{method}','AutocompleteController@search');

Route::post('role/createpermissionrole', ['as' => 'role.createpermissionrole', 'uses' => 'RoleController@createpermissionrole']);

Route::get('role/load-data', 'RoleController@loadData');
Route::get('permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::get('role/permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::resource('role', 'RoleController');
Route::delete('role/{id}/restore', 'RoleController@restore');

Route::get('permission-role/load-data', 'PermissionRoleController@loadData');
Route::resource('permission-role', 'PermissionRoleController');
Route::delete('permission-role/{id}/restore', 'PermissionRoleController@restore');

Route::get('menu/load-data','MenuController@loadData');
Route::resource('menu','MenuController');
Route::delete('menu/{id}/restore','MenuController@restore');

Route::get('permission/load-data','PermissionController@loadData');
Route::resource('permission','PermissionController');
Route::delete('permission/{id}/restore','PermissionController@restore');

Route::get('status-pegawai/load-data','StatusPegawaiController@loadData');
Route::resource('status-pegawai','StatusPegawaiController');
Route::delete('status-pegawai/{id}/restore','StatusPegawaiController@restore');

Route::get('golongan/load-data','GolonganController@loadData');
Route::resource('golongan','GolonganController');
Route::delete('golongan/{id}/restore','GolonganController@restore');

Route::get('jabatan/load-data','JabatanController@loadData');
Route::resource('jabatan','JabatanController');
Route::delete('jabatan/{id}/restore','JabatanController@restore');

Route::get('unit-kerja/load-data','UnitKerjaController@loadData');
Route::resource('unit-kerja','UnitKerjaController');
Route::delete('unit-kerja/{id}/restore','UnitKerjaController@restore');

Route::get('golongan-darah/load-data','GolonganDarahController@loadData');
Route::resource('golongan-darah','GolonganDarahController');
Route::delete('golongan-darah/{id}/restore','GolonganDarahController@restore');

Route::get('agama/load-data','AgamaController@loadData');
Route::resource('agama','AgamaController');
Route::delete('agama/{id}/restore','AgamaController@restore');


Route::get('status-pernikahan/load-data','StatusPernikahanController@loadData');
Route::resource('status-pernikahan','StatusPernikahanController');
Route::delete('status-pernikahan/{id}/restore','StatusPernikahanController@restore');

Route::get('provinsi/load-data','ProvinsiController@loadData');
Route::resource('provinsi','ProvinsiController');
Route::delete('provinsi/{id}/restore','ProvinsiController@restore');

Route::get('kabupaten/load-data','KabupatenController@loadData');
Route::resource('kabupaten','KabupatenController');
Route::delete('kabupaten/{id}/restore','KabupatenController@restore');

Route::get('kecamatan/load-data','KecamatanController@loadData');
Route::resource('kecamatan','KecamatanController');
Route::delete('kecamatan/{id}/restore','KecamatanController@restore');

Route::get('kelurahan/load-data','KelurahanController@loadData');
Route::resource('kelurahan','KelurahanController');
Route::delete('kelurahan/{id}/restore','KelurahanController@restore');

Route::get('pegawai/load-data','PegawaiController@loadData');
Route::get('tambah-pegawai','PegawaiController@create');
Route::resource('pegawai','PegawaiController');
Route::delete('pegawai/{id}/restore','PegawaiController@restore');

Route::get('/tambah-penduduk','PendudukController@createPenduduk');
Route::get('autocomplete/{method}','AutocompleteController@search');
Route::get('dropdown/{method}','DropDownController@index');

Route::get('/profile','PendudukController@loadProfile');
Route::get('penduduk/load-agama','PendudukController@loadAgama');
Route::get('penduduk/load-golongan-darah','PendudukController@loadGolonganDarah');
Route::get('penduduk/load-status','PendudukController@loadStatus');
Route::get('penduduk/load-pekerjaan','PendudukController@loadPekerjaan');
Route::get('penduduk/load-jk','PendudukController@loadJenisKelamin');
Route::get('penduduk/load-provinsi','PendudukController@loadProvinsi');
Route::get('penduduk/get-kabupaten', 'PendudukController@getKabupaten');
Route::get('penduduk/get-kecamatan', 'PendudukController@getKecamatan');
Route::get('penduduk/get-kelurahan', 'PendudukController@getKelurahan');
Route::match(['get', 'post'],'penduduk/upload-foto','PendudukController@uploadFoto');
Route::match(['get', 'post'],'penduduk/simpan-pelamar','PendudukController@simpan');
Route::match(['get', 'post'],'penduduk/simpan-penduduk','PendudukController@simpanData');
Route::get('penduduk/delete-foto','PendudukController@deleteFoto');
Route::get('penduduk/load-data','PendudukController@loadData');
Route::resource('penduduk','PendudukController');
Route::delete('penduduk/{id}/restore','PendudukController@restore');



Route::get('perusahaan/load-data','PerusahaanController@loadData');
Route::resource('perusahaan','PerusahaanController');
Route::delete('perusahaan/{id}/restore','PerusahaanController@restore');


Route::get('kategori-news/load-data','KategoriNewsController@loadData');
Route::resource('kategori-news','KategoriNewsController');
Route::delete('kategori-news/{id}/restore','KategoriNewsController@restore');

Route::get('news/load-data','NewsController@loadData');
Route::resource('news','NewsController');
Route::delete('news/{id}/restore','NewsController@restore');

Route::get('jabatan/load-data','JabatanController@loadData');
Route::resource('jabatan','JabatanController');
Route::delete('jabatan/{id}/restore','JabatanController@restore');

Route::get('golongan-darah/load-data','GolonganDarahController@loadData');
Route::resource('golongan-darah','GolonganDarahController');
Route::delete('golongan-darah/{id}/restore','GolonganDarahController@restore');

Route::get('unit-kerja/load-data','UnitKerjaController@loadData');
Route::resource('unit-kerja','UnitKerjaController');
Route::delete('unit-kerja/{id}/restore','UnitKerjaController@restore');

Route::get('jenis-kelamin/load-data','JenisKelaminController@loadData');
Route::resource('jenis-kelamin','JenisKelaminController');
Route::delete('jenis-kelamin/{id}/restore','JenisKelaminController@restore');

Route::get('status-pernikahan/load-data','StatusPernikahanController@loadData');
Route::resource('status-pernikahan','StatusPernikahanController');
Route::delete('status-pernikahan/{id}/restore','StatusPernikahanController@restore');

Route::get('/pengaturan', 'ConfigIdController@settings')->name('settings');
Route::get('/delete-logo', 'ConfigIdController@deleteLogo');
Route::get('config-id/load-data','ConfigIdController@loadData');
Route::resource('config-id','ConfigIdController');
Route::delete('config-id/{id}/restore','ConfigIdController@restore');

Route::get('profesi/load-data','ProfesiController@loadData');
Route::resource('profesi','ProfesiController');
Route::delete('profesi/{id}/restore','ProfesiController@restore');

Route::get('status-pegawai/load-data','StatusPegawaiController@loadData');
Route::resource('status-pegawai','StatusPegawaiController');
Route::delete('status-pegawai/{id}/restore','StatusPegawaiController@restore');

Route::get('lihat-pegawai/{id}','PegawaiController@lihatPegawai');
Route::get('edit-pegawai/{id}','PegawaiController@editPegawai');
Route::get('tambah-pegawai','PegawaiController@tambahPegawai');
Route::get('pegawai/load-data','PegawaiController@loadData');
Route::resource('pegawai','PegawaiController');
Route::delete('pegawai/{id}/restore','PegawaiController@restore');

Route::get('kategori-kasus/load-data','KategoriKasusController@loadData');
Route::resource('kategori-kasus','KategoriKasusController');
Route::delete('kategori-kasus/{id}/restore','KategoriKasusController@restore');

Route::get('edit-rekam-kasus/{id}','RekamKasusController@editData');
Route::get('tambah-rekam-kasus','RekamKasusController@tambahData');
Route::match(['get', 'post'],'rekam-kasus/simpan-kasus','RekamKasusController@simpanData');

Route::get('rekam-kasus/load-data','RekamKasusController@loadData');
Route::resource('rekam-kasus','RekamKasusController');
Route::delete('rekam-kasus/{id}/restore','RekamKasusController@restore');

Route::get('bp/load-data','BpController@loadData');
Route::resource('bp','BpController');
Route::delete('bp/{id}/restore','BpController@restore');

Route::get('petum/load-data','PetumController@loadData');
Route::resource('petum','PetumController');
Route::delete('petum/{id}/restore','PetumController@restore');

Route::get('map/load-data','MapController@loadData');
Route::resource('map','MapController');
Route::delete('map/{id}/restore','MapController@restore');

Route::get('sub-kategori-kasus/load-data','SubKategoriKasusController@loadData');
Route::resource('sub-kategori-kasus','SubKategoriKasusController');
Route::delete('sub-kategori-kasus/{id}/restore','SubKategoriKasusController@restore');

Route::get('laporan-rekam-kasus','LaporanController@indexLaporanRekamKasus');
Route::get('laporan-rekam-kasus/load-data','LaporanController@loadDataLaporanRekamKasus');
Route::get('laporan-rekam-kasus/cetak/{date_from}/{date_to}/{kategori}','LaporanController@cetakLaporanRekamKasus');

app/Http/Controllers/KelurahanController.php
<?php
namespace App\Http\Controllers;

use App\Models\Kelurahan;
use App\Models\Kecamatan;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Datatables;

class KelurahanController extends Controller
{
  public $viewDir = "kelurahan";
  public $breadcrumbs = array(
   'permissions'=>array('title'=>'Kelurahan','link'=>"#",'active'=>false,'display'=>true),
 );

  public function __construct()
  {
    $this->middleware('auth');
   $this->middleware('permission:read-kelurahan');
 }

 public function index()
 {
   return $this->view( "index");
 }

       /**
        * Show the form for creating a new resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function create()
       {
         $data=array(
           'kelurahan'=>new Kelurahan,
           'kecamatan'=>new Kecamatan,
         );
         return $this->view("form",$data);
       }

       /**
        * Store a newly created resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function store( Request $request )
       {
         $this->validate($request, Kelurahan::validationRules());

         $act=Kelurahan::create($request->all());
         message($act,'Data Kelurahan berhasil ditambahkan','Data Kelurahan gagal ditambahkan');
         return redirect('kelurahan');
       }

       /**
        * Display the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function show(Request $request, $kode)
       {
         $kelurahan=Kelurahan::find($kode);
         return $this->view("show",['kelurahan' => $kelurahan]);
       }

       /**
        * Show the form for editing the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function edit(Request $request, $kode)
       {
         $kelurahan=Kelurahan::find($kode);
         $kecamatan=Kecamatan::find($kelurahan->id_kecamatan);
         $data=array(
           'kelurahan'=>$kelurahan,
           'kecamatan'=>$kecamatan,
         );
         return $this->view( "form", $data );
       }

       /**
        * Update the specified resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function update(Request $request, $kode)
       {
         $kelurahan=Kelurahan::find($kode);
         if( $request->isXmlHttpRequest() )
         {
           $data = [$request->name  => $request->value];
           $validator = \Validator::make( $data, Kelurahan::validationRules( $request->name ) );
           if($validator->fails())
             return response($validator->errors()->first( $request->name),403);
           $kelurahan->update($data);
           return "Record updated";
         }
         $this->validate($request, Kelurahan::validationRules());

         $act=$kelurahan->update($request->all());
         message($act,'Data Kelurahan berhasil diupdate','Data Kelurahan gagal diupdate');

         return redirect('/kelurahan');
       }

       /**
        * Remove the specified resource from storage.
        *
        * @return  \Illuminate\Http\Response
        */
       public function destroy(Request $request, $kode)
       {
         $kelurahan=Kelurahan::find($kode);
         $act=false;
         try {
           $act=$kelurahan->forceDelete();
         } catch (\Exception $e) {
           $kelurahan=Kelurahan::find($kelurahan->pk());
           $act=$kelurahan->delete();
         }
       }

       protected function view($view, $data = [])
       {
         return view($this->viewDir.".".$view, $data);
       }
       public function loadData()
       {
         $GLOBALS['nomor']=\Request::input('start',1)+1;
         $dataList = Kelurahan::select('*');
         if (request()->get('status') == 'trash') {
           $dataList->onlyTrashed();
         }
         return Datatables::of($dataList)
         ->addColumn('nomor',function($kategori){
           return $GLOBALS['nomor']++;
         })

         ->addColumn('kecamatan',function($data){
          if(isset($data->kecamatan->kecamatan)){

            return $data->kecamatan->kecamatan;
          }else {
            return null;
          }
       })
         ->addColumn('kabupaten',function($data){
          if(isset($data->kecamatan->kabupaten->kabupaten)){

            return $data->kecamatan->kabupaten->kabupaten;
          }else {
            return null;
          }
       })

       ->addColumn('provinsi',function($data){
        if(isset($data->kecamatan->kabupaten->provinsi->provinsi)){

          return $data->kecamatan->kabupaten->provinsi->provinsi;
        }else {
          return null;
        }
     })
         ->addColumn('action', function ($data) {
           $edit=url("kelurahan/".$data->pk())."/edit";
           $delete=url("kelurahan/".$data->pk());
           $content = '';
           $content .= "<a onclick='show_modal(\"$edit\")' class='btn btn-sm btn-icon btn-pure btn-default on-default edit-row ' data-toggle='tooltip' data-original-title='Edit'><i class='icon md-edit' aria-hidden='true'></i></a>";
           $content .= " <a onclick='hapus(\"$delete\")' class='btn btn-sm btn-icon btn-pure btn-default on-default remove-row' data-toggle='tooltip' data-original-title='Remove'><i class='icon md-delete' aria-hidden='true'></i></a>";

           return $content;
         })
         ->make(true);  
       }

       
    }

resources/views/kelurahan/index.blade.php
@extends('layouts.app')

@section('content')
   <div class="page-header">
     <h1 class="page-title">Kelurahan</h1>
      @include('layouts.inc.breadcrumb')
     <div class="page-header-actions">
     <a class="btn btn-block btn-primary data-modal" id="data-modal" href="#" onclick="show_modal('{{ route('kelurahan.create') }}')" >Tambah</a>
     </div>
   </div>
   <div class="page-content">
     <!-- Panel Table Tools -->
     <div class="panel">
       <header class="panel-heading">
         <div class="form-group col-md-12">
           <div class="form-group">
         <!-- <h3 class="panel-title">Table Tools</h3> -->

           </div>
         </div>
       </header>
       <div class="panel-body">
         <!-- <table class="table table-bordered" id="users-table">

         </table> -->
         <table class="table table-hover dataTable table-striped w-full" id="kelurahan-table">
           <thead>
               <tr>
                 <th>No</th>
                                           <th>Kode Kelurahan</th>
                                           <th>Provinsi</th>
                                           <th>Kabupaten</th>
                                           <th>Kecamatan</th>
                                    <th>Kelurahan</th>
                                    {{-- <th>flag_aktif</th> --}}
                                    <th>Kodepos</th>
                                    {{-- <th>created_at</th> --}}
                             <th>Aksi</th>
               </tr>
           </thead>
         </table>
       </div>
     </div>
     <!-- End Panel Table Tools -->
 </div>
 <div class="modal fade" id="formModal" aria-hidden="true" aria-labelledby="formModalLabel" role="dialog" tabindex="-1">
 </div>

@endsection

@push('js')
<script type="text/javascript">
$(function() {
  $('.trash-ck').click(function(){
    if ($('.trash-ck').prop('checked')) {
      document.location = '{{ url("kelurahan?status=trash") }}';
    } else {
      document.location = '{{ url("kelurahan") }}';
    }
  });
    $('#kelurahan-table').DataTable({
      stateSave: true,
    processing : true,
    serverSide : true,
    pageLength:20,
        ajax : {
                  url:"{{ url('kelurahan/load-data') }}",
                data: function (d) {

                }
      },
        columns: [
          { data: 'nomor', name: 'nomor',searchable:false,orderable:false },
                                      { data: 'kode', name: 'kode' },
                      { data: 'provinsi', name: 'provinsi' },
                      { data: 'kabupaten', name: 'kabupaten' },
                      { data: 'kecamatan', name: 'kecamatan' },
                      { data: 'kelurahan', name: 'kelurahan' },
                      // { data: 'flag_aktif', name: 'flag_aktif' },
                      { data: 'kodepos', name: 'kodepos' },
                      // { data: 'created_at', name: 'created_at' },
                      { data: 'action', name: 'action', orderable: false, searchable: false },
      ],
      language: {
            lengthMenu : '{{ "Menampilkan _MENU_ data" }}',
            zeroRecords : '{{ "Data tidak ditemukan" }}' ,
            info : '{{ "_PAGE_ dari _PAGES_ halaman" }}',
            infoEmpty : '{{ "Data tidak ditemukan" }}',
            infoFiltered : '{{ "(Penyaringan dari _MAX_ data)" }}',
            loadingRecords : '{{ "Memuat data dari server" }}' ,
            processing :    '{{ "Memuat data data" }}',
            search :        '{{ "Pencarian:" }}',
            paginate : {
                first :     '{{ "<" }}' ,
                last :      '{{ ">" }}' ,
                next :      '{{ ">>" }}',
                previous :  '{{ "<<" }}'
            }
        },
        aoColumnDefs: [{
          bSortable: false,
          aTargets: [-1]
        }],
        iDisplayLength: 5,
        aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
        // sDom: '<"dt-panelmenu clearfix"Bfr>t<"dt-panelfooter clearfix"ip>',
        // buttons: ['copy', 'excel', 'csv', 'pdf', 'print'],
    });
});
</script>
@endpush